services:
  archiver:
    build: .
    environment:
      WIKIPEDIA_LAG_CHECKER_CONFIG: /app/config/default.toml
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
    restart: unless-stopped
